Update exercise files

diff --git a/.github/workflows/enforce-folder-permissions-push.yml b/.github/workflows/enforce-folder-permissions-push.yml
--- a/.github/workflows/enforce-folder-permissions-push.yml
+++ b/.github/workflows/enforce-folder-permissions-push.yml
@@ -16,10 +16,48 @@ jobs:
       with:
         fetch-depth: 2
 
-    - name: Set Environment Variables
+    # Log the event name and event path for debugging purposes
+    - name: Log Event Name and Path
       run: |
-        echo "AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
+        echo "Event Name: ${{ github.event_name }}"
+        echo "Event Path: $GITHUB_EVENT_PATH"
+        cat $GITHUB_EVENT_PATH
+
+    # Extract and log details from Git history to find the main contributor
+    - name: Identify the Main Contributor from the Merge
+      env:
+        TOKEN_USER_READ: ${{ secrets.TOKEN_USER_READ }}
+      run: |
+        # Get the latest commit hash from the current branch (usually main after a merge)
+        COMMIT_HASH=$(git rev-parse HEAD)
+
+        # Get repository owner and name from the current Git context
+        REPO=$(basename `git rev-parse --show-toplevel`)
+        OWNER=$(git remote get-url origin | sed -n 's#.*github.com[:/]\(.*\)/.*#\1#p')
+
+        echo "Fetching GitHub username for commit: $COMMIT_HASH"
+
+        # Use the GitHub Commit API to get commit details
+        COMMIT_API_URL="https://api.github.com/repos/$OWNER/$REPO/commits/$COMMIT_HASH"
+        COMMIT_DETAILS=$(curl -s -H "Authorization: token $TOKEN_USER_READ" $COMMIT_API_URL)
+
+        # Extract the commit author's GitHub username from the API response
+        USER_LOGIN=$(echo "$COMMIT_DETAILS" | jq -r '.author.login')
+
+        # Check if the username was successfully determined
+        if [ -n "$USER_LOGIN" ] && [ "$USER_LOGIN" != "null" ]; then
+          echo "GitHub Username successfully determined: $USER_LOGIN"
+          echo "AUTHOR=$USER_LOGIN" >> $GITHUB_ENV
+        else
+          echo "Failed to determine GitHub username for commit $COMMIT_HASH"
+          exit 1
+        fi
+
+    # Log the repository name for further use
+    - name: Log Repository Name
+      run: |
         echo "GITHUB_REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV
+        echo "Repository Name: ${{ env.GITHUB_REPOSITORY_NAME }}"
 
     - name: Setup AWS CLI
       uses: aws-actions/configure-aws-credentials@v1
